import Foundation

/// Extended description of the film, including information about the budget,
/// production companies, production countries, revenue, and status.
struct DetailedMovie: Codable {
    /// Indicates if the movie is for adults.
    let adult: Bool

    /// The budget of the movie in the specified currency (usually USD).
    let budget: Int

    /// Genres associated with the movie.
    let genres: [Genre]

    /// The unique identifier of the movie.
    let id: Int

    /// The countries where the movie was produced.
    let originCountry: [String]

    /// The original language of the movie.
    let originalLanguage: String

    /// The title of the movie.
    let title: String

    /// A brief overview or synopsis of the movie.
    let overview: String

    /// The popularity score of the movie.
    let popularity: Double

    /// The path to the poster image of the movie. This can be combined with a base URL to form the full URL.
    let posterPath: String?

    /// The path to the backdrop image of the movie. This can be combined with a base URL to form the full URL.
    let backdropPath: String?

    /// The release date of the movie in the format "YYYY-MM-DD".
    let releaseDate: String

    /// Duration of the movie.
    let runTime: Int

    /// Production companies involved in making the movie.
    let productionCompanies: [ProductionCompany]

    /// Countries involved in making the movie.
    let productionCountries: [ProductionCountry]

    /// The total revenue generated by the movie in the specified currency (usually USD).
    let revenue: Int

    /// The current status of the movie (e.g., "Released", "Post Production").
    let status: String

    /// The tagline or catchphrase associated with the movie.
    let tagline: String?

    /// The average vote score of the movie.
    let voteAverage: Double
}
